---
title: "EDA"
author: "Stanly Palathingal"
date: "26 February 2020"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/HP/OneDrive - Newcastle University/Group project")
```


```{r, include=FALSE}
library(magrittr)
library(dplyr)
```

```{r}
A= read.csv("Data/A.csv")
B= read.csv("Data/B.csv")
P= read.csv("Data/Power.csv")
```

```{r}
dim(A)
dim(B)
dim(P)

```


```{r}
summary(A)
```

```{r}
summary(B)
```

```{r}
summary(P)
```
There are six rows with no values and considering the number of rows they can be eliminated. In A there are 4, abd the otehr two have 6 null rows.
```{r}
A=na.omit(A)
B=na.omit(B)
P=na.omit(P)
```

Sclaed the values to make all under a specific range

```{r}
A_scaled=scale(x=A[,3:26],scale=TRUE)
cov(A_scaled)%>% round(2) %>% View()
```

# in file B

```{r}
B_scaled=scale(x=B[,3:32],scale=TRUE)
cov(B_scaled)%>% round(2) %>% View()
```

```{r}
colnames(B)
```
The 'AIRCON_REQUEST_NODE_' values are there only for 3 nodes
The nodes 4,5 and 6 are always 0

```{r}
filter(B,AIRCON_REQUEST_NODE_1 == 1)%>%View()
```

```{r}
filter(B,AIRCON_REQUEST_NODE_2 == 1)%>%View()
```

```{r}
filter(B,AIRCON_REQUEST_NODE_3 == 1)%>%View()
```

