---
title: "group project Stack 3"
author: "Stanly Palathingal"
date: "26 February 2020"
output: pdf_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/HP/OneDrive - Newcastle University/Group project")
```
Define the working directory. There are three directories. 
    First is the git directory. 
    second is the datast. 
    Third is the data folder where the combine data will be stored.

```{r}
library(plyr)
library(readr)
library(magrittr)
```


```{r run only the first time}

A_K2 = list.files(path="Dataset/Stack_3", pattern="*A_K2.csv", full.names=TRUE)
B_K2 = list.files(path="Dataset/Stack_3", pattern="*B_K2.csv", full.names=TRUE)
Power = list.files(path="Dataset/Stack_3", pattern="*POWER.csv", full.names=TRUE)

A_K2 %>% ldply(read.csv) %>% write.csv("Data/A.csv",row.names = FALSE)
B_K2 %>% ldply(read.csv) %>% write.csv("Data/B.csv",row.names = FALSE)
Power %>% ldply(read.csv) %>% write.csv("Data/Power.csv",row.names = FALSE)
```





